title: 'Ary Mega'
logo: 
description: "I'm Ary, an American-Indonesian father, fiancé, product designer and front-end developer from Los Angeles, California."
keywords:
baseurl: ""
url: "https://arymega.com"


# Siteheader Settings
siteheader:
  name: 'Ary Mega'
  image: https://media.giphy.com/media/5n067EUZwH8cvtRfGz/giphy.gif
  title: "👋 I'm Ary."
  slogan: "An American-Indonesian father, fiancé, product designer and front-end web developer from Los Angeles, California. If you need to holler, you can <a href='https://www.google.com/search?sxsrf=ALeKk00JrX_sOee4LZVBN-29IALbSc2zLQ%3A1582267624362&source=hp&ei=6HxPXoDVEpba-gStoYyQBA&q=%40awwwry&oq=%40awwwry&gs_l=psy-ab.3..35i39.294.1364..1526...1.0..0.162.717.5j2......0....1..gws-wiz.......0j0i131j0i30j0i10i30j0i5i10i30.04UbNZaqF0E&ved=0ahUKEwiA6b6dhuLnAhUWrZ4KHa0QA0IQ4dUDCAc&uact=5' target='_blank'>find me all over the internet.</a>"
  email:


# Contact links
contact:
  - name: GitHub
    link: 
  - name: Instagram
    link: 
  - name: LinkedIn
    link: 
  - name: Merch
    link: 
  - name: Reddit
    link: 
  - name: Spotify
    link: 
  - name: Twitter
    link: 


# Comment Section (Disqus)
disqus-identifier:


# Google Analytics
google-analytics:


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never


# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []