# Your Name or Company
title: Ary Mega

# Description of your website. This is used for social sharing.
description:  An American-Indonesian father, fiancé, product designer and front-end developer from Los Angeles, California.

# A brief blurb about yourself
content: An American-Indonesian father, fiancé, product designer and front-end developer from Los Angeles, California.

# Add your social links
social:
  - platform: github
    url: https://github.com/awwwry
  - platform: twitter
    url: https://twitter.com/awwwry
  - platform: linkedin
    url: awwwry

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
